---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	prepare(prepare)
	supervisor(supervisor)
	technical(technical)
	market(market)
	stakeholder(stakeholder)
	domain(domain)
	trl(trl)
	synthesis(synthesis)
	report(report)
	quality(quality)
	save(save)
	__end__([<p>__end__</p>]):::last
	__start__ --> prepare;
	domain --> supervisor;
	market --> supervisor;
	prepare --> supervisor;
	quality --> supervisor;
	report --> supervisor;
	stakeholder --> supervisor;
	supervisor -.-> domain;
	supervisor -.-> market;
	supervisor -.-> quality;
	supervisor -.-> report;
	supervisor -.-> save;
	supervisor -.-> stakeholder;
	supervisor -.-> synthesis;
	supervisor -.-> technical;
	supervisor -.-> trl;
	synthesis --> supervisor;
	technical --> supervisor;
	trl --> supervisor;
	save --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
